set -g default-terminal "screen-256color"
set-option -a terminal-features 'screen-256color:RGB'
set-environment -g COLORTERM "truecolor"

set-option -g allow-passthrough on

# Nvim suggestions
set-option -g focus-events on

set -g status-keys vi
set-option -g history-limit 64096
set-window-option -g xterm-keys on

# Auto title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Prefix
unbind C-b
set-option -g prefix M-Space
bind M-Space send-prefix

# Splitting
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Primitive window-cycling
bind -r p select-window -t :-
bind -r n select-window -t :+

# Panes
setw -g pane-base-index 1

bind o run-shell "open #{pane_current_path}"
bind -r M-q kill-pane -a

bind -r K resize-pane -U
bind -r J resize-pane -D
bind -r H resize-pane -L
bind -r L resize-pane -R

bind -rn M-K resize-pane -U 5
bind -rn M-J resize-pane -D 5
bind -rn M-H resize-pane -L 5
bind -rn M-L resize-pane -R 5

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -rn M-k select-pane -U
bind -rn M-j select-pane -D
bind -rn M-h select-pane -L
bind -rn M-l select-pane -R

bind = select-layout tiled

# Windows
set -g base-index 1

bind -nr M-p previous-window
bind -nr M-n next-window

# Delay between prefix and command
set -sg escape-time 1

# Load config
bind r source-file ~/.tmux.conf

# Theme
set -g mode-style "fg=colour8,bg=colour14"

set -g message-style "fg=colour8,bg=colour14"
set -g message-command-style "fg=colour8,bg=colour14"

set -g pane-border-style "fg=colour14"
set -g pane-active-border-style "fg=colour8,bold"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "bg=default"

set -g status-bg "default"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=colour16,bg=colour12,bold]  TMUX  #[fg=colour12,bg=default,nobold,nounderscore,noitalics]#[fg=colour13,bg=default,bold]  #(whoami) #[fg=default,bg=default,nobold] "
set -g status-right ""

setw -g window-status-activity-style "underscore,fg=default,bg=default"
setw -g window-status-separator "  "
setw -g window-status-style "NONE,fg=default,bg=default"
setw -g window-status-format '#[default] #I #{b:pane_current_command}@#{s|$HOME|~|;s|/.*/|/…/|:pane_current_path}'
setw -g window-status-current-format '#[fg=colour3,bg=default,bold]  #I #[italics]#{b:pane_current_command}@#{s|$HOME|~|;s|/.*/|/…/|:pane_current_path}  '
