# BEGIN_ALACRITTY_THEME
general.import = [ "~/.config/alacritty/dark.toml" ]
# END_ALACRITTY_THEME

[font]
size = 10.0
offset.y = 20
offset.x = 1
glyph_offset.y = 10

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
blur = true
option_as_alt = "Both"

[window.padding]
x = 8
y = 8
