[colors.primary]
background = "#262626"
foreground = "#f6f6f6"
dim_foreground = "#4f4f4f"
bright_foreground = "#b0b0b0"

[colors.cursor]
text = "#451203"
cursor = "#feecc7"

[colors.vi_mode_cursor]
text = "#172254"
cursor = "#dbe8fe"

[colors.search.matches]
foreground = "#231a4c"
background = "#dfe3ff"

[colors.search.focused_match]
foreground = "#1e280b"
background = "#edf4d3"

[colors.footer_bar]
foreground = "#122e3a"
background = "#d7f2f6"

[colors.hints.start]
foreground = "#422406"
background = "#fefdc3"

[colors.hints.end]
foreground = "#122e3a"
background = "#d7f2f6"

[colors.selection]
text = "#471408"
background = "#ffe7e1"

[colors.normal]
black = "#3d3d3d"
red = "#fd876c"
green = "#b6d167"
yellow = "#f9db16"
blue = "#5f9efb"
magenta = "#837ffa"
cyan = "#45b6cb"
white = "#d1d1d1"

[colors.bright]
black = "#454545"
red = "#ffb4a3"
green = "#c4dc7a"
yellow = "#fdec47"
blue = "#a2c9fe"
magenta = "#a3a8fe"
cyan = "#81d3e0"
white = "#e7e7e7"

[[colors.indexed_colors]]
index = 16
color = "#fcd88b"

[[colors.indexed_colors]]
index = 17
color = "#ffd2c8"
