[colors.primary]
background = "#f6f6f6"
foreground = "#262626"
dim_foreground = "#3d3d3d"
bright_foreground = "#4f4f4f"

[colors.cursor]
text = "#feecc7"
cursor = "#451203"

[colors.vi_mode_cursor]
text = "#dbe8fe"
cursor = "#172254"

[colors.search.matches]
foreground = "#dfe3ff"
background = "#231a4c"

[colors.search.focused_match]
foreground = "#edf4d3"
background = "#1e280b"

[colors.footer_bar]
foreground = "#d7f2f6"
background = "#122e3a"

[colors.hints.start]
foreground = "#fefdc3"
background = "#422406"

[colors.hints.end]
foreground = "#d7f2f6"
background = "#122e3a"

[colors.selection]
background = "#ffe7e1"
text = "#471408"

[colors.normal]
black = "#3d3d3d"
red = "#9d3017"
green = "#44551f"
yellow = "#85550e"
blue = "#1d38b0"
magenta = "#442ea5"
cyan = "#265464"
white = "#b0b0b0"

[colors.bright]
black = "#454545"
red = "#e24420"
green = "#6e8b25"
yellow = "#ca9704"
blue = "#2358ed"
magenta = "#6043e8"
cyan = "#257d95"
white = "#d1d1d1"

[[colors.indexed_colors]]
index = 16
color = "#fcd88b"

[[colors.indexed_colors]]
index = 17
color = "#9d3017"

